<input type="hidden" value="welcome" alt="Programming processing with blocks" id="exercise_name">
<xml id="startBlocks" style="display: none">
<block type="processing" x="113" y="63">
    <statement name="SETUP">
      <block type="size">
        <value name="width">
          <block type="math_number">
            <field name="NUM">300</field>
          </block>
        </value>
        <value name="height">
          <block type="math_number">
            <field name="NUM">400</field>
          </block>
        </value>
      </block>
    </statement>
    <statement name="DRAW">
    </statement>
  </block>
 </xml>